USE salon_db;

CREATE TABLE IF NOT EXISTS user (
  id MEDIUMINT NOT NULL AUTO_INCREMENT UNIQUE ,
  role TINYINT NOT NULL CHECK (`role` IN (0, 1)),
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  login VARCHAR(30) NOT NULL UNIQUE ,
  password VARCHAR(30),
  discount INTEGER(99),
  PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS balance (
  id MEDIUMINT NOT NULL AUTO_INCREMENT UNIQUE,
  user_id MEDIUMINT UNIQUE,
  current_balance DOUBLE,
  overdruft DOUBLE,
  PRIMARY KEY(id),
  FOREIGN KEY (user_id) REFERENCES user (id)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS user_order (
  id MEDIUMINT NOT NULL  AUTO_INCREMENT UNIQUE ,
  paid BOOLEAN,
  total_price DOUBLE NOT NULL,
  date DATE,
  user_id MEDIUMINT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES user (id)
)ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS souvenir (
  id MEDIUMINT NOT NULL AUTO_INCREMENT UNIQUE,
  size MEDIUMINT NOT NULL,
  color VARCHAR(30) NOT NULL,
  image VARCHAR(300) NOT NULL,
  price MEDIUMINT NOT NULL,
  author_id MEDIUMINT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (author_id) REFERENCES user (id)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS souvenir_order (
  order_id MEDIUMINT NOT NULL,
  souvenir_id MEDIUMINT NOT NULL,
  PRIMARY KEY (order_id,souvenir_id),
  FOREIGN KEY (order_id) REFERENCES user_order (id),
  FOREIGN KEY (souvenir_id) REFERENCES souvenir (id)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;